import { describe, expect, test } from "bun:test"

import { PROJECT_GITIGNORE_FILENAME, PROJECT_GITIGNORE_RULES, renderProjectGitignore } from "./gitignore"

describe("PROJECT_GITIGNORE_RULES", () => {
  test("carries every rule storage-identity §13 and turn-durability §3.1 name", () => {
    for (const rule of [
      "/lock",
      "/workspace.local.toml",
      "*.local*",
      "/transactions.local/",
      "/**/.termcraft-tx-*.tmp",
      "/cache/",
      "/diagnostics/",
      "/logs/",
      "/backups/",
      "/backup-*",
    ]) {
      expect(PROJECT_GITIGNORE_RULES).toContain(rule)
    }
  })

  test("is duplicate-free and deterministic in order", () => {
    expect(new Set(PROJECT_GITIGNORE_RULES).size).toBe(PROJECT_GITIGNORE_RULES.length)
    expect(PROJECT_GITIGNORE_RULES).toEqual(PROJECT_GITIGNORE_RULES)
  })

  test("anchors every project-root-relative rule with a leading slash", () => {
    // Only the `*.local*` family and the `/**/` depth-independent globs are unanchored:
    // §13 excludes those at ANY depth, not just at the `.termcraft/` root.
    const unanchored = PROJECT_GITIGNORE_RULES.filter((rule) => !rule.startsWith("/"))
    expect(unanchored).toEqual(["*.local*"])
  })
})

describe("renderProjectGitignore", () => {
  test("is byte-deterministic and ends with a trailing newline", () => {
    const text = renderProjectGitignore()
    expect(text).toBe(renderProjectGitignore())
    expect(text.endsWith("\n")).toBe(true)
  })

  test("contains every rule on its own line", () => {
    const lines = renderProjectGitignore().split("\n")
    for (const rule of PROJECT_GITIGNORE_RULES) expect(lines).toContain(rule)
  })

  test("carries a generated-file notice pointing at StoragePathPolicy as the real authority", () => {
    const text = renderProjectGitignore()
    expect(text).toContain("# Generated by termcraft")
    expect(text).toContain("StoragePathPolicy")
  })

  test("never ignores a portable path (§13: project.toml and .gitignore are commit-eligible)", () => {
    for (const rule of PROJECT_GITIGNORE_RULES) {
      expect(rule).not.toBe("/project.toml")
      expect(rule).not.toBe("/.gitignore")
      expect(rule).not.toBe("/chats/")
      expect(rule).not.toBe("/pages/")
      expect(rule).not.toBe("/export/")
    }
  })

  test("the generated file is named .gitignore", () => {
    expect(PROJECT_GITIGNORE_FILENAME).toBe(".gitignore")
  })
})
