/** The generated ignore file's name inside `.termcraft/` (storage-identity §13). */
export const PROJECT_GITIGNORE_FILENAME = ".gitignore";

/**
 * The generated `.termcraft/.gitignore` rule set, mirroring the `StoragePathPolicy` hard
 * exclusions of storage-identity §13 plus the transaction-specific reserved names of
 * turn-durability §3.1.
 *
 * AUTHORITY NOTE (§13, verbatim): "The generated `.gitignore` contains matching anchored
 * rules for user visibility, but correctness rests on `StoragePathPolicy`." This file is a
 * courtesy mirror — a path denied by policy stays denied even if it is tracked,
 * force-added, or re-included by a `.gitignore` negation. `StoragePathPolicy` itself is a
 * live commit planner and is out of MVP scope (phase-4 plan, Deferred), so no code here
 * depends on this list for correctness.
 *
 * Rules are anchored to `.termcraft/` (the directory holding the generated file) with a
 * leading `/`, except the `*.local*` family, which §13 excludes at ANY depth.
 *
 * Row by row against §13's hard-exclusion list:
 * - `lock` — the `ProjectLease` file (§9).
 * - `workspace.local.toml` plus `*.local*`, covering "every `*.local` or `*.local.*` file,
 *   and every directory whose name ends in `.local`".
 * - `chats/` — AMENDED 2026-07-26 (MVP blocker fix bundle §2.5, and storage-identity §13's own
 *   list amended alongside it). The spec previously classified chats as portable; chat logs churn
 *   on every turn and can carry arbitrary user text, so they move to hard-local. Nothing breaks
 *   on the clone side: `active_chat_id` lives in `workspace.local.toml`, already hard-local via
 *   `/workspace.local.toml` and `*.local*`, so a clone carries no pointer to a chat file it lacks.
 * - `transactions.local/` and the depth-independent `.termcraft-tx-*.tmp` glob — the two
 *   reserved names turn-durability §3.1 adds; the Git adapter rejects them independently.
 * - `cache/`, `diagnostics/`, `logs/` — the rebuildable projection and observability trees.
 * - `backups/` and `backup-*` — §13's defensive matches for migration or repair backups
 *   that appear under `.termcraft/` despite the required external placement (§12).
 * - `.tmp-*` at any depth — "temporary, swap, and atomic-replacement files created by
 *   ProjectStore"; this is the prefix `infrastructure/durability`'s `durableFileWrite`
 *   uses for its same-directory staging file.
 *
 * "Every path outside `.termcraft/`" is the last §13 exclusion; it is a policy rule about
 * scope membership, not something a `.gitignore` inside `.termcraft/` can express, so it
 * has no row here.
 */
export const PROJECT_GITIGNORE_RULES: readonly string[] = [
  "/lock",
  "/workspace.local.toml",
  "*.local*",
  "/chats/",
  "/transactions.local/",
  "/**/.termcraft-tx-*.tmp",
  "/**/.tmp-*",
  "/cache/",
  "/diagnostics/",
  "/logs/",
  "/backups/",
  "/backup-*",
];

const HEADER_LINES: readonly string[] = [
  "# Generated by termcraft — do not edit.",
  "# Machine-local paths under .termcraft/ (storage-identity design §13,",
  "# turn-durability design §3.1). These rules exist for user visibility only:",
  "# commit-scope correctness rests on StoragePathPolicy, which denies these paths",
  "# even when they are tracked, force-added, or re-included by a negation.",
];

/**
 * Render the generated `.termcraft/.gitignore` (storage-identity §13). Byte-deterministic:
 * fixed header, fixed rule order, single trailing newline — so regenerating it on an
 * unchanged policy produces no diff.
 */
export function renderProjectGitignore(): string {
  return [...HEADER_LINES, "", ...PROJECT_GITIGNORE_RULES, ""].join("\n");
}
