// Regenerates src/libs.generated.ts.
//
// How the embedded lib list is determined (do not hand-maintain it):
// `lib.esnext.d.ts` is not one file — it is the root of a chain of
// `/// <reference lib="..." />` directives. A missing link does not surface as
// "file not found"; it surfaces as a confusing "cannot find name X". So the list
// is enumerated by transitively following those directives from the root, over
// the *installed* platform package, and emitted as one Bun file-import per file.
//
// Cross-check: the chain this produces (87 files) matches exactly the set of
// lib.*.d.ts paths the Go compiler asks the virtual FS for at runtime (87 reads).
//
// Run: bun run src/gen-libs.ts
import fs from "node:fs"
import path from "node:path"

const libDir = path.resolve("node_modules/@typescript/typescript-win32-x64/lib")
const seen = new Set<string>()
const order: string[] = []

function visit(name: string) {
  if (seen.has(name)) return
  seen.add(name)
  const src = fs.readFileSync(path.join(libDir, name), "utf8")
  for (const m of src.matchAll(/\/\/\/\s*<reference\s+lib\s*=\s*"([^"]+)"\s*\/>/g)) {
    visit(`lib.${m[1]}.d.ts`)
  }
  order.push(name) // post-order: dependencies first
}

visit("lib.esnext.d.ts")

// The Go compiler's startup check (internal/bundled, noembed build) stats `lib.d.ts`
// next to the exe and panics "this executable may be misplaced" if it is absent. It is
// only an existence sentinel: with `lib: ["esnext"]` the default lib is overridden, so
// its own chain (es5/dom/webworker/scripthost) is never parsed and is NOT followed here.
const SENTINEL = "lib.d.ts"
if (!seen.has(SENTINEL)) {
  seen.add(SENTINEL)
  order.push(SENTINEL)
}

const ident = (n: string) => "lib_" + n.replace(/^lib\./, "").replace(/\.d\.ts$/, "").replace(/[.-]/g, "_")
const rel = "../node_modules/@typescript/typescript-win32-x64/lib"

const lines = [
  "// GENERATED by src/gen-libs.ts — do not edit.",
  '// The transitive `/// <reference lib="..." />` chain rooted at lib.esnext.d.ts,',
  "// enumerated from the installed typescript@7.0.2 platform package,",
  `// plus the lib.d.ts startup sentinel. ${order.length} files.`,
  "",
  ...order.map((n) => `import ${ident(n)} from "${rel}/${n}" with { type: "file" }`),
  "",
  '/** basename -> embedded file path (a B:/~BUN/root/... path inside a compiled binary) */',
  "export const embeddedLibs: Record<string, string> = {",
  ...order.map((n) => `  ${JSON.stringify(n)}: ${ident(n)},`),
  "}",
  "",
  `export const embeddedLibNames: readonly string[] = ${JSON.stringify(order, null, 2)}`,
  "",
]

fs.writeFileSync("src/libs.generated.ts", lines.join("\n"))
console.log("wrote src/libs.generated.ts with", order.length, "lib imports")
