// GENERATED by src/gen-libs.ts — do not edit.
// The transitive `/// <reference lib="..." />` chain rooted at lib.esnext.d.ts,
// enumerated from the installed typescript@7.0.2 platform package,
// plus the lib.d.ts startup sentinel. 88 files.

import lib_decorators from "../node_modules/@typescript/typescript-win32-x64/lib/lib.decorators.d.ts" with { type: "file" }
import lib_decorators_legacy from "../node_modules/@typescript/typescript-win32-x64/lib/lib.decorators.legacy.d.ts" with { type: "file" }
import lib_es5 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es5.d.ts" with { type: "file" }
import lib_es2015_core from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.core.d.ts" with { type: "file" }
import lib_es2015_collection from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.collection.d.ts" with { type: "file" }
import lib_es2015_symbol from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.symbol.d.ts" with { type: "file" }
import lib_es2015_iterable from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.iterable.d.ts" with { type: "file" }
import lib_es2015_generator from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.generator.d.ts" with { type: "file" }
import lib_es2015_promise from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.promise.d.ts" with { type: "file" }
import lib_es2015_proxy from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.proxy.d.ts" with { type: "file" }
import lib_es2015_reflect from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.reflect.d.ts" with { type: "file" }
import lib_es2015_symbol_wellknown from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.symbol.wellknown.d.ts" with { type: "file" }
import lib_es2015 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2015.d.ts" with { type: "file" }
import lib_es2016_array_include from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2016.array.include.d.ts" with { type: "file" }
import lib_es2016_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2016.intl.d.ts" with { type: "file" }
import lib_es2016 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2016.d.ts" with { type: "file" }
import lib_es2017_arraybuffer from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2017.arraybuffer.d.ts" with { type: "file" }
import lib_es2017_date from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2017.date.d.ts" with { type: "file" }
import lib_es2017_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2017.intl.d.ts" with { type: "file" }
import lib_es2017_object from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2017.object.d.ts" with { type: "file" }
import lib_es2017_sharedmemory from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2017.sharedmemory.d.ts" with { type: "file" }
import lib_es2017_string from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2017.string.d.ts" with { type: "file" }
import lib_es2017_typedarrays from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2017.typedarrays.d.ts" with { type: "file" }
import lib_es2017 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2017.d.ts" with { type: "file" }
import lib_es2018_asynciterable from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2018.asynciterable.d.ts" with { type: "file" }
import lib_es2018_asyncgenerator from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2018.asyncgenerator.d.ts" with { type: "file" }
import lib_es2018_promise from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2018.promise.d.ts" with { type: "file" }
import lib_es2018_regexp from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2018.regexp.d.ts" with { type: "file" }
import lib_es2018_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2018.intl.d.ts" with { type: "file" }
import lib_es2018 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2018.d.ts" with { type: "file" }
import lib_es2019_array from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2019.array.d.ts" with { type: "file" }
import lib_es2019_object from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2019.object.d.ts" with { type: "file" }
import lib_es2019_string from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2019.string.d.ts" with { type: "file" }
import lib_es2019_symbol from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2019.symbol.d.ts" with { type: "file" }
import lib_es2019_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2019.intl.d.ts" with { type: "file" }
import lib_es2019 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2019.d.ts" with { type: "file" }
import lib_es2020_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2020.intl.d.ts" with { type: "file" }
import lib_es2020_bigint from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2020.bigint.d.ts" with { type: "file" }
import lib_es2020_date from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2020.date.d.ts" with { type: "file" }
import lib_es2020_number from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2020.number.d.ts" with { type: "file" }
import lib_es2020_promise from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2020.promise.d.ts" with { type: "file" }
import lib_es2020_sharedmemory from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2020.sharedmemory.d.ts" with { type: "file" }
import lib_es2020_symbol_wellknown from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2020.symbol.wellknown.d.ts" with { type: "file" }
import lib_es2020_string from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2020.string.d.ts" with { type: "file" }
import lib_es2020 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2020.d.ts" with { type: "file" }
import lib_es2021_promise from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2021.promise.d.ts" with { type: "file" }
import lib_es2021_string from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2021.string.d.ts" with { type: "file" }
import lib_es2021_weakref from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2021.weakref.d.ts" with { type: "file" }
import lib_es2021_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2021.intl.d.ts" with { type: "file" }
import lib_es2021 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2021.d.ts" with { type: "file" }
import lib_es2022_array from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2022.array.d.ts" with { type: "file" }
import lib_es2022_error from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2022.error.d.ts" with { type: "file" }
import lib_es2022_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2022.intl.d.ts" with { type: "file" }
import lib_es2022_object from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2022.object.d.ts" with { type: "file" }
import lib_es2022_regexp from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2022.regexp.d.ts" with { type: "file" }
import lib_es2022_string from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2022.string.d.ts" with { type: "file" }
import lib_es2022 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2022.d.ts" with { type: "file" }
import lib_es2023_array from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2023.array.d.ts" with { type: "file" }
import lib_es2023_collection from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2023.collection.d.ts" with { type: "file" }
import lib_es2023_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2023.intl.d.ts" with { type: "file" }
import lib_es2023 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2023.d.ts" with { type: "file" }
import lib_es2024_arraybuffer from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2024.arraybuffer.d.ts" with { type: "file" }
import lib_es2024_collection from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2024.collection.d.ts" with { type: "file" }
import lib_es2024_object from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2024.object.d.ts" with { type: "file" }
import lib_es2024_promise from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2024.promise.d.ts" with { type: "file" }
import lib_es2024_regexp from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2024.regexp.d.ts" with { type: "file" }
import lib_es2024_sharedmemory from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2024.sharedmemory.d.ts" with { type: "file" }
import lib_es2024_string from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2024.string.d.ts" with { type: "file" }
import lib_es2024 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2024.d.ts" with { type: "file" }
import lib_es2025_collection from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2025.collection.d.ts" with { type: "file" }
import lib_es2025_float16 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2025.float16.d.ts" with { type: "file" }
import lib_es2025_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2025.intl.d.ts" with { type: "file" }
import lib_es2025_iterator from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2025.iterator.d.ts" with { type: "file" }
import lib_es2025_promise from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2025.promise.d.ts" with { type: "file" }
import lib_es2025_regexp from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2025.regexp.d.ts" with { type: "file" }
import lib_es2025 from "../node_modules/@typescript/typescript-win32-x64/lib/lib.es2025.d.ts" with { type: "file" }
import lib_esnext_temporal from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.temporal.d.ts" with { type: "file" }
import lib_esnext_intl from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.intl.d.ts" with { type: "file" }
import lib_esnext_collection from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.collection.d.ts" with { type: "file" }
import lib_esnext_decorators from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.decorators.d.ts" with { type: "file" }
import lib_esnext_disposable from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.disposable.d.ts" with { type: "file" }
import lib_esnext_array from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.array.d.ts" with { type: "file" }
import lib_esnext_error from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.error.d.ts" with { type: "file" }
import lib_esnext_sharedmemory from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.sharedmemory.d.ts" with { type: "file" }
import lib_esnext_typedarrays from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.typedarrays.d.ts" with { type: "file" }
import lib_esnext_date from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.date.d.ts" with { type: "file" }
import lib_esnext from "../node_modules/@typescript/typescript-win32-x64/lib/lib.esnext.d.ts" with { type: "file" }
import lib_d_ts from "../node_modules/@typescript/typescript-win32-x64/lib/lib.d.ts" with { type: "file" }

/** basename -> embedded file path (a B:/~BUN/root/... path inside a compiled binary) */
export const embeddedLibs: Record<string, string> = {
  "lib.decorators.d.ts": lib_decorators,
  "lib.decorators.legacy.d.ts": lib_decorators_legacy,
  "lib.es5.d.ts": lib_es5,
  "lib.es2015.core.d.ts": lib_es2015_core,
  "lib.es2015.collection.d.ts": lib_es2015_collection,
  "lib.es2015.symbol.d.ts": lib_es2015_symbol,
  "lib.es2015.iterable.d.ts": lib_es2015_iterable,
  "lib.es2015.generator.d.ts": lib_es2015_generator,
  "lib.es2015.promise.d.ts": lib_es2015_promise,
  "lib.es2015.proxy.d.ts": lib_es2015_proxy,
  "lib.es2015.reflect.d.ts": lib_es2015_reflect,
  "lib.es2015.symbol.wellknown.d.ts": lib_es2015_symbol_wellknown,
  "lib.es2015.d.ts": lib_es2015,
  "lib.es2016.array.include.d.ts": lib_es2016_array_include,
  "lib.es2016.intl.d.ts": lib_es2016_intl,
  "lib.es2016.d.ts": lib_es2016,
  "lib.es2017.arraybuffer.d.ts": lib_es2017_arraybuffer,
  "lib.es2017.date.d.ts": lib_es2017_date,
  "lib.es2017.intl.d.ts": lib_es2017_intl,
  "lib.es2017.object.d.ts": lib_es2017_object,
  "lib.es2017.sharedmemory.d.ts": lib_es2017_sharedmemory,
  "lib.es2017.string.d.ts": lib_es2017_string,
  "lib.es2017.typedarrays.d.ts": lib_es2017_typedarrays,
  "lib.es2017.d.ts": lib_es2017,
  "lib.es2018.asynciterable.d.ts": lib_es2018_asynciterable,
  "lib.es2018.asyncgenerator.d.ts": lib_es2018_asyncgenerator,
  "lib.es2018.promise.d.ts": lib_es2018_promise,
  "lib.es2018.regexp.d.ts": lib_es2018_regexp,
  "lib.es2018.intl.d.ts": lib_es2018_intl,
  "lib.es2018.d.ts": lib_es2018,
  "lib.es2019.array.d.ts": lib_es2019_array,
  "lib.es2019.object.d.ts": lib_es2019_object,
  "lib.es2019.string.d.ts": lib_es2019_string,
  "lib.es2019.symbol.d.ts": lib_es2019_symbol,
  "lib.es2019.intl.d.ts": lib_es2019_intl,
  "lib.es2019.d.ts": lib_es2019,
  "lib.es2020.intl.d.ts": lib_es2020_intl,
  "lib.es2020.bigint.d.ts": lib_es2020_bigint,
  "lib.es2020.date.d.ts": lib_es2020_date,
  "lib.es2020.number.d.ts": lib_es2020_number,
  "lib.es2020.promise.d.ts": lib_es2020_promise,
  "lib.es2020.sharedmemory.d.ts": lib_es2020_sharedmemory,
  "lib.es2020.symbol.wellknown.d.ts": lib_es2020_symbol_wellknown,
  "lib.es2020.string.d.ts": lib_es2020_string,
  "lib.es2020.d.ts": lib_es2020,
  "lib.es2021.promise.d.ts": lib_es2021_promise,
  "lib.es2021.string.d.ts": lib_es2021_string,
  "lib.es2021.weakref.d.ts": lib_es2021_weakref,
  "lib.es2021.intl.d.ts": lib_es2021_intl,
  "lib.es2021.d.ts": lib_es2021,
  "lib.es2022.array.d.ts": lib_es2022_array,
  "lib.es2022.error.d.ts": lib_es2022_error,
  "lib.es2022.intl.d.ts": lib_es2022_intl,
  "lib.es2022.object.d.ts": lib_es2022_object,
  "lib.es2022.regexp.d.ts": lib_es2022_regexp,
  "lib.es2022.string.d.ts": lib_es2022_string,
  "lib.es2022.d.ts": lib_es2022,
  "lib.es2023.array.d.ts": lib_es2023_array,
  "lib.es2023.collection.d.ts": lib_es2023_collection,
  "lib.es2023.intl.d.ts": lib_es2023_intl,
  "lib.es2023.d.ts": lib_es2023,
  "lib.es2024.arraybuffer.d.ts": lib_es2024_arraybuffer,
  "lib.es2024.collection.d.ts": lib_es2024_collection,
  "lib.es2024.object.d.ts": lib_es2024_object,
  "lib.es2024.promise.d.ts": lib_es2024_promise,
  "lib.es2024.regexp.d.ts": lib_es2024_regexp,
  "lib.es2024.sharedmemory.d.ts": lib_es2024_sharedmemory,
  "lib.es2024.string.d.ts": lib_es2024_string,
  "lib.es2024.d.ts": lib_es2024,
  "lib.es2025.collection.d.ts": lib_es2025_collection,
  "lib.es2025.float16.d.ts": lib_es2025_float16,
  "lib.es2025.intl.d.ts": lib_es2025_intl,
  "lib.es2025.iterator.d.ts": lib_es2025_iterator,
  "lib.es2025.promise.d.ts": lib_es2025_promise,
  "lib.es2025.regexp.d.ts": lib_es2025_regexp,
  "lib.es2025.d.ts": lib_es2025,
  "lib.esnext.temporal.d.ts": lib_esnext_temporal,
  "lib.esnext.intl.d.ts": lib_esnext_intl,
  "lib.esnext.collection.d.ts": lib_esnext_collection,
  "lib.esnext.decorators.d.ts": lib_esnext_decorators,
  "lib.esnext.disposable.d.ts": lib_esnext_disposable,
  "lib.esnext.array.d.ts": lib_esnext_array,
  "lib.esnext.error.d.ts": lib_esnext_error,
  "lib.esnext.sharedmemory.d.ts": lib_esnext_sharedmemory,
  "lib.esnext.typedarrays.d.ts": lib_esnext_typedarrays,
  "lib.esnext.date.d.ts": lib_esnext_date,
  "lib.esnext.d.ts": lib_esnext,
  "lib.d.ts": lib_d_ts,
}

export const embeddedLibNames: readonly string[] = [
  "lib.decorators.d.ts",
  "lib.decorators.legacy.d.ts",
  "lib.es5.d.ts",
  "lib.es2015.core.d.ts",
  "lib.es2015.collection.d.ts",
  "lib.es2015.symbol.d.ts",
  "lib.es2015.iterable.d.ts",
  "lib.es2015.generator.d.ts",
  "lib.es2015.promise.d.ts",
  "lib.es2015.proxy.d.ts",
  "lib.es2015.reflect.d.ts",
  "lib.es2015.symbol.wellknown.d.ts",
  "lib.es2015.d.ts",
  "lib.es2016.array.include.d.ts",
  "lib.es2016.intl.d.ts",
  "lib.es2016.d.ts",
  "lib.es2017.arraybuffer.d.ts",
  "lib.es2017.date.d.ts",
  "lib.es2017.intl.d.ts",
  "lib.es2017.object.d.ts",
  "lib.es2017.sharedmemory.d.ts",
  "lib.es2017.string.d.ts",
  "lib.es2017.typedarrays.d.ts",
  "lib.es2017.d.ts",
  "lib.es2018.asynciterable.d.ts",
  "lib.es2018.asyncgenerator.d.ts",
  "lib.es2018.promise.d.ts",
  "lib.es2018.regexp.d.ts",
  "lib.es2018.intl.d.ts",
  "lib.es2018.d.ts",
  "lib.es2019.array.d.ts",
  "lib.es2019.object.d.ts",
  "lib.es2019.string.d.ts",
  "lib.es2019.symbol.d.ts",
  "lib.es2019.intl.d.ts",
  "lib.es2019.d.ts",
  "lib.es2020.intl.d.ts",
  "lib.es2020.bigint.d.ts",
  "lib.es2020.date.d.ts",
  "lib.es2020.number.d.ts",
  "lib.es2020.promise.d.ts",
  "lib.es2020.sharedmemory.d.ts",
  "lib.es2020.symbol.wellknown.d.ts",
  "lib.es2020.string.d.ts",
  "lib.es2020.d.ts",
  "lib.es2021.promise.d.ts",
  "lib.es2021.string.d.ts",
  "lib.es2021.weakref.d.ts",
  "lib.es2021.intl.d.ts",
  "lib.es2021.d.ts",
  "lib.es2022.array.d.ts",
  "lib.es2022.error.d.ts",
  "lib.es2022.intl.d.ts",
  "lib.es2022.object.d.ts",
  "lib.es2022.regexp.d.ts",
  "lib.es2022.string.d.ts",
  "lib.es2022.d.ts",
  "lib.es2023.array.d.ts",
  "lib.es2023.collection.d.ts",
  "lib.es2023.intl.d.ts",
  "lib.es2023.d.ts",
  "lib.es2024.arraybuffer.d.ts",
  "lib.es2024.collection.d.ts",
  "lib.es2024.object.d.ts",
  "lib.es2024.promise.d.ts",
  "lib.es2024.regexp.d.ts",
  "lib.es2024.sharedmemory.d.ts",
  "lib.es2024.string.d.ts",
  "lib.es2024.d.ts",
  "lib.es2025.collection.d.ts",
  "lib.es2025.float16.d.ts",
  "lib.es2025.intl.d.ts",
  "lib.es2025.iterator.d.ts",
  "lib.es2025.promise.d.ts",
  "lib.es2025.regexp.d.ts",
  "lib.es2025.d.ts",
  "lib.esnext.temporal.d.ts",
  "lib.esnext.intl.d.ts",
  "lib.esnext.collection.d.ts",
  "lib.esnext.decorators.d.ts",
  "lib.esnext.disposable.d.ts",
  "lib.esnext.array.d.ts",
  "lib.esnext.error.d.ts",
  "lib.esnext.sharedmemory.d.ts",
  "lib.esnext.typedarrays.d.ts",
  "lib.esnext.date.d.ts",
  "lib.esnext.d.ts",
  "lib.d.ts"
]
