export type { CapturedFrame, RenderHandle, RenderSize } from "./types"
export { rgbaToColor } from "./model/color"
export { attributesToMask } from "./model/attributes"
export { styledRowsFromSpanLines } from "./model/span-rows"
export { makeHeadlessStreams } from "./model/streams"
