// Regenerates `scripts/tsc-lib-sources/*.d.ts.txt` and `scripts/tsc-libs.generated.ts`. Runs
// automatically via `package.json`'s `postinstall` (so a fresh `bun install` always produces
// them); re-run manually (`bun run scripts/gen-tsc-libs.ts`) after bumping the pinned
// `typescript`/`@typescript/typescript-win32-x64` version. Both outputs are gitignored —
// reproducible from the installed platform package, never hand-edited, never vendored.
//
// WHY a generator, not a hand-written list (Spike C, docs/spikes/03-tsc-in-binary/FINDINGS.md
// "The embedded lib file list — 88 files"): `lib.esnext.d.ts` is not one file — it is the root
// of a chain of `/// <reference lib="..." />` directives, and a missing link surfaces as a
// confusing "cannot find name X" rather than an honest "file not found". So the list is
// enumerated by transitively following those directives from the root, over the *installed*
// platform package, rather than transcribed by hand (a transcription slip would be silent).
// `scripts/lib-cross-check.ts` is the completeness safety net for when this list goes stale
// relative to a newer installed compiler.
//
// WHY the `.d.ts.txt` copies, not a direct `with { type: "file" }` import of the real
// `lib.*.d.ts` path (a divergence from Spike C's own `libs.generated.ts`, which imported
// node_modules directly): TypeScript's own checker hard-rejects importing a file whose
// extension literally ends `.d.ts` as a value — "TS2846: a declaration file cannot be imported
// without 'import type'" — REGARDLESS of the `with { type: "file" }` attribute, and regardless
// of any ambient `declare module` pattern (verified empirically; see the WP-11 report). `import
// type` would erase the import at compile time, losing the runtime path string this whole
// mechanism needs. Renaming the copy so its extension is `.txt` (never treated as a TypeScript
// declaration file) sidesteps the rule entirely; `scripts/file-assets.d.ts`'s `declare module
// "*.txt"` types the result as the plain string Bun actually returns.
import fs from "node:fs";
import path from "node:path";

const LIB_DIR = path.resolve("node_modules/@typescript/typescript-win32-x64/lib");
const SOURCES_DIR = path.resolve("scripts/tsc-lib-sources");
const OUT_FILE = path.resolve("scripts/tsc-libs.generated.ts");
const REFERENCE_RE = /\/\/\/\s*<reference\s+lib\s*=\s*"([^"]+)"\s*\/>/g;

if (!fs.existsSync(LIB_DIR)) {
  // Global Constraints: only Windows is in scope for this MVP (Spike C concern #2 — the lib
  // import path is platform-specific). On any other OS/arch this optional platform package is
  // never installed, and `postinstall` must not fail the whole `bun install` over that.
  console.warn(
    `scripts/gen-tsc-libs.ts: ${LIB_DIR} not found (non-Windows host?) — skipping; the Gate's ` +
      "embedded type-check assets will be unavailable on this machine.",
  );
  process.exit(0);
}

/** The startup sentinel (Spike C): the Go compiler's `noembed` build stats `lib.d.ts` next to
 *  its own exe before any API/virtual-FS exists, and panics if it is absent. It is never
 *  *read* for content — `lib: ["esnext"]` overrides the default lib, so its own chain
 *  (es5/dom/webworker/scripthost) is never parsed and is deliberately not followed here. */
const SENTINEL = "lib.d.ts";

function walkReferenceChain(root: string): string[] {
  const seen = new Set<string>();
  const order: string[] = [];

  function visit(name: string): void {
    if (seen.has(name)) return;
    seen.add(name);
    const source = fs.readFileSync(path.join(LIB_DIR, name), "utf8");
    for (const match of source.matchAll(REFERENCE_RE)) {
      visit(`lib.${match[1]}.d.ts`);
    }
    order.push(name); // post-order: dependencies before dependents
  }

  visit(root);
  return order;
}

const chain = walkReferenceChain("lib.esnext.d.ts");
const names = chain.includes(SENTINEL) ? chain : [...chain, SENTINEL];

fs.mkdirSync(SOURCES_DIR, { recursive: true });
for (const name of names) {
  fs.copyFileSync(path.join(LIB_DIR, name), path.join(SOURCES_DIR, `${name}.txt`));
}

const toIdentifier = (name: string): string =>
  `lib_${name
    .replace(/^lib\./, "")
    .replace(/\.d\.ts$/, "")
    .replace(/[.-]/g, "_")}`;

const lines = [
  "// GENERATED by scripts/gen-tsc-libs.ts — do not hand-edit. Gitignored: reproduced from the",
  "// installed @typescript/typescript-win32-x64 package on every `bun install` (postinstall).",
  "//",
  '// The transitive `/// <reference lib="..." />` chain rooted at lib.esnext.d.ts, walked over',
  "// the installed platform package, plus the lib.d.ts startup sentinel (Spike C).",
  `// ${names.length} files. Each import points at a \`.d.ts.txt\` copy under`,
  "// scripts/tsc-lib-sources/, not the real .d.ts path — see this file's own header comment",
  "// for why (TypeScript's TS2846 forbids importing a literal .d.ts as a value).",
  "",
  ...names.map(
    (name) =>
      `import ${toIdentifier(name)} from "./tsc-lib-sources/${name}.txt" with { type: "file" };`,
  ),
  "",
  '/** Embedded lib basename -> its `with { type: "file" }` path (real in dev, `B:/~BUN/...`',
  " *  or `/$bunfs/...` once `bun build --compile`d). */",
  "export const tscLibPaths: Readonly<Record<string, string>> = {",
  ...names.map((name) => `  ${JSON.stringify(name)}: ${toIdentifier(name)},`),
  "};",
  "",
  "/** The curated set's names, in dependency order (post-order: deps before dependents). */",
  `export const tscLibNames: readonly string[] = ${JSON.stringify(names, null, 2)};`,
  "",
];

fs.writeFileSync(OUT_FILE, lines.join("\n"));
console.log(
  `wrote ${OUT_FILE} and ${names.length} files under ${SOURCES_DIR} (${names.length} embedded lib imports)`,
);
