// Real JSX, exactly as the spec says a saved page looks: NO explicit react/jsx-runtime
// import. The jsx-runtime helper import is generated by the transform, not written here.
import { Panel, kitApiVersion } from "@termcraft/runtime"

export const meta = { title: "JSX probe", kitApiVersion }

export default function Page() {
  return <Panel id="root" title="hello from JSX" />
}
