// Fix 1: does compiler-owned JSX work under fallback (a)?
//
// The page's jsx-runtime helper import is GENERATED by the transform, not written by the
// author. That generated bare specifier must resolve into the host — the same failure class
// the naive probe caught. Two modes:
//   bare      : only the @termcraft/runtime resolver is registered (what Spike A tested).
//   with-jsx  : additionally registers react/jsx-runtime + react/jsx-dev-runtime.
//   dev-only  : registers ONLY react/jsx-dev-runtime — the specifier the transform actually
//               generates — leaving the author-written react/jsx-runtime unresolvable.
//               This is the candidate that may satisfy BOTH halves of spec :679-680.
//
// usage: probe-jsx <abs-path-to-page.tsx> [bare|with-jsx|dev-only]
import { plugin } from "bun"
import * as runtime from "./runtime.ts"
import { pathToFileURL } from "node:url"

const pagePath = process.argv[2]
const mode = process.argv[3] ?? "bare"
if (!pagePath) {
  console.error("usage: probe-jsx <absolute-path-to-page.tsx> [bare|with-jsx]")
  process.exit(2)
}

// Which helper the transform actually reaches for is itself a finding, so instrument each.
const calls: string[] = []

plugin({
  name: "termcraft-runtime-resolver",
  setup(build) {
    build.module("@termcraft/runtime", () => ({
      exports: runtime,
      loader: "object",
    }))
  },
})

if (mode === "with-jsx" || mode === "dev-only") {
  const h =
    (name: string) =>
    (type: unknown, props: Record<string, unknown>): unknown => {
      calls.push(name)
      return typeof type === "function"
        ? (type as (p: unknown) => unknown)(props)
        : String(type)
    }
  const jsxRuntime = {
    jsx: h("jsx"),
    jsxs: h("jsxs"),
    jsxDEV: h("jsxDEV"),
    Fragment: (props: { children?: unknown }) => {
      calls.push("Fragment")
      return props?.children
    },
  }
  plugin({
    name: "termcraft-jsx-runtime",
    setup(build) {
      // dev-only deliberately does NOT register react/jsx-runtime, so an author who writes
      // that import explicitly still gets a resolve failure.
      if (mode === "with-jsx") {
        build.module("react/jsx-runtime", () => ({
          exports: jsxRuntime,
          loader: "object",
        }))
      }
      build.module("react/jsx-dev-runtime", () => ({
        exports: jsxRuntime,
        loader: "object",
      }))
    },
  })
}

try {
  const mod = await import(pathToFileURL(pagePath).href)
  console.log(
    JSON.stringify({
      ok: true,
      mode,
      helpersCalled: calls,
      meta: mod.meta,
      rendered: typeof mod.default === "function" ? mod.default() : null,
    }),
  )
} catch (e) {
  console.log(
    JSON.stringify({
      ok: false,
      mode,
      helpersCalled: calls,
      name: (e as Error).name,
      message: (e as Error).message,
    }),
  )
  process.exit(1)
}
