import type { DesignSystemManifestV1 } from "../types";

/**
 * `design/system/design-system.json`'s exact bytes. Two-space JSON with a trailing newline —
 * the same shape `entities/design-tree`'s `encodePagesManifest` produces for `pages.json`, so the
 * two files written into one design tree read the same way in a diff.
 *
 * BYTE-DETERMINISTIC, which is load-bearing twice: the file's bytes fold into `treeRevision`
 * (`entities/design-tree`'s `computeTreeRevision`), so a non-deterministic renderer would
 * invalidate the host's session key for nothing; and the migration's transaction CASes on the hash
 * of what it is about to write.
 */
export function renderDesignSystemManifest(manifest: DesignSystemManifestV1): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/**
 * `design/system/tokens.ts`'s exact bytes — the §4.3 scaffold, verbatim from the spec.
 *
 * THE MAPPED TYPE IS THE WHOLE POINT. A JSON import widens every string value to `string` under
 * `resolveJsonModule`, which is not assignable to `Color`; a bare indexed access
 * (`(typeof ds)["themes"]["dark"]["tokens"]`) would carry that widened type straight into every
 * colour prop and fail every `t.<token>` read. The mapped type re-types each value as `Color` while
 * keeping the key set derived from the manifest, so a typo'd key is still a fatal type error.
 *
 * THE DEFAULT THEME'S LITERAL NAME is written into the indexed access — `manifest.defaultTheme`,
 * never a fixed `"dark"`. With cross-theme parity enforced (§4.2, P2's decoder) every theme has the
 * same key set, so the derived type is correct for whichever theme is active.
 */
export function renderTokensScaffold(manifest: DesignSystemManifestV1): string {
  return [
    `// Generated by termcraft. The token NAMES and VALUES live in ./design-system.json — edit that`,
    `// file (or ask the design agent to) and this accessor follows automatically.`,
    `import { useTokens as useRuntimeTokens, type Color } from "@termcraft/runtime"`,
    `import ds from "./design-system.json"`,
    ``,
    `export type Tokens = { [K in keyof (typeof ds)["themes"]["${manifest.defaultTheme}"]["tokens"]]: Color }`,
    `export const useTokens = () => useRuntimeTokens<Tokens>()`,
    ``,
  ].join("\n");
}
